
export const START_LOADING = "STATUS/START_LOADING";
export const END_LOADING = "STATUS/END_LOADING";
export const ALERT_ERROR = "STATUS/ALERT_ERROR";


export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const GET_PRODUCTS_CATEGORY = "GET_PRODUCTS_CATEGORY";
export const GET_SORTED_PRODUCTS = "GET_SORTED_PRODUCTS";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PAGE_PRODUCTS = "GET_PAGE_PRODUCTS";







